export const demoBriefs = {
  geopolitics: {
    kicker: "Geopolitics · demo content",
    summary: "A useful geopolitical brief should show what changed, who is affected, and where the uncertainty still sits — not just repeat the loudest headline.",
    stories: [
      { title: "Diplomacy is often the story between the headlines", body: "The production feed retrieves current coverage across regions, clusters related reporting and asks the model to separate observable developments from interpretation.", sources: [] },
      { title: "Perspective matters", body: "SETU’s prompt asks the summarizer to identify when different sources frame the same development differently and to avoid presenting contested claims as settled fact.", sources: [] },
      { title: "Follow the consequences", body: "Each item ends with a short ‘why students should care’ line connecting global developments to research, mobility, technology, energy or society.", sources: [] }
    ]
  },
  science: {
    kicker: "Academic & scientific · demo content",
    summary: "The science lens prioritizes discoveries, major papers, research policy and academic developments — with a bias toward explaining evidence rather than amplifying hype.",
    stories: [
      { title: "Claims are not conclusions", body: "Production summaries can label whether an item is a peer-reviewed result, preprint, institutional announcement or secondary report.", sources: [] },
      { title: "Read the method", body: "For research stories, the brief asks what was measured, what the comparison was and what the study cannot yet establish.", sources: [] },
      { title: "Turn news into learning", body: "One click can send any science story to Paper Decoder or Depth Dial for a deeper student-facing explanation.", sources: [] }
    ]
  },
  economy: {
    kicker: "Economy · demo content",
    summary: "The economic lens focuses on policy, inflation, trade, labour, technology and markets while separating measured indicators from predictions.",
    stories: [
      { title: "Start with the number and the population", body: "A strong brief states what changed, over what period, and for whom before adding interpretation.", sources: [] },
      { title: "Markets are not the whole economy", body: "The feed balances market moves with policy, employment, industrial and household-level developments.", sources: [] },
      { title: "Forecasts stay attributed", body: "Predictions are presented as forecasts from named institutions or analysts, not as facts generated by the model.", sources: [] }
    ]
  }
};

export const signals = [
  { tag: "Opportunity", title: "Student research lightning talks", body: "A lightweight format for 5-minute research ideas, negative results and paper explainers." },
  { tag: "Peer learning", title: "Teach one thing you know", body: "Offer a 30-minute micro-session and let interested students join a tiny cohort." },
  { tag: "Build", title: "Campus micro-tool challenge", body: "Ship a small utility that removes one daily friction point for students." }
];

export const campusModules = [
  { icon: "↗", title: "Opportunities", body: "Scholarships, internships, research calls, hackathons and campus roles.", action: "Browse board" },
  { icon: "∞", title: "Peer learning", body: "Host or join short student-led sessions around one precise skill.", action: "Find a session" },
  { icon: "◇", title: "Clubs & events", body: "A simple, searchable calendar instead of scattered message threads.", action: "Open calendar" },
  { icon: "⌖", title: "Lost & found", body: "Post and match lost items without exposing unnecessary personal information.", action: "Open board" },
  { icon: "⚙", title: "Campus utilities", body: "Quick links, forms, transport notes, lab information and common services.", action: "Open utilities" },
  { icon: "✣", title: "Idea wall", body: "Suggest one small improvement and let students add context, not outrage.", action: "Add an idea" },
  { icon: "◌", title: "Skill exchange", body: "Trade knowledge: ‘I can teach X; I want to learn Y.’", action: "Create exchange" },
  { icon: "⌁", title: "Project commons", body: "Find collaborators for course, research and open-source projects.", action: "Find collaborators" }
];

export const aiTools = {
  socratic: { title: "Socratic Coach", description: "Tell SETU what you are learning. It should ask one useful question at a time and avoid giving the final answer too early.", label: "Problem, concept or attempted solution", level: false },
  explain: { title: "Depth Dial", description: "Choose the level, then ask for an explanation that builds intuition before formalism.", label: "Concept to explain", level: true },
  paper: { title: "Paper Decoder", description: "Paste an abstract or short passage. SETU will unpack prerequisites, central claim, method, evidence, limitations and questions to ask next.", label: "Abstract or research passage", level: false },
  debate: { title: "Debate Lens", description: "Enter a debatable claim. SETU will steelman distinct positions, identify assumptions and generate neutral questions for discussion.", label: "Claim or question", level: false },
  map: { title: "Concept Mapper", description: "Turn a topic into a dependency map with prerequisites, milestones, misconceptions and a small capstone task.", label: "Topic to map", level: true },
  oral: { title: "Viva Simulator", description: "Enter a topic and answer the generated questions aloud. The prototype returns an opening viva sequence and evaluation rubric.", label: "Viva topic", level: true }
};

export const pollSeed = [
  { id: "research", label: "Research lightning talks", votes: 14 },
  { id: "fitness", label: "Weekly sport / fitness hour", votes: 9 },
  { id: "skills", label: "Student skill-exchange sessions", votes: 18 },
  { id: "openhouse", label: "Monthly student–faculty open house", votes: 11 }
];
